
biome-distribution:
  # Biome distribution refers to the placement of biomes, this does *NOT*
  # include aspects like terrain height / shape within biomes, or anything
  # else that generates within any given biome.
  
  # These parameters are designed to allow for easy modification of biome distribution,
  # and are injected into the various biome distribution configs via meta-configuration.
  # You can find these configs in the biome-providers directory, most of which contain
  # additional more specific parameters.
  
  continental-scale: 100
  # Controls the scale of land / coastal / oceanic distribution. Increasing
  # this produces larger landmasses and larger oceans, and vice-versa when
  # decreasing it.
  # Default: 100

  # temperature-scale: 60
  # # Controls the scale of temperature zones. Most biomes are placed according to
  # # a temperature map so hot biomes can't generate next to cold biomes, as well as
  # # allowing for biomes of similar temperatures to generate together. Increasing this
  # # will increase the distance between temperature changes, which results in things like
  # # hot and cold biomes generating further apart - and vice versa when decreasing it.
  # # Default: 60

  # precipitation-scale: 50
  # # Controls the scale of precipitation zones. Same idea as temperature zones, where
  # # humid biomes generate away from arid biomes, and biomes of similar precipitation
  # # generate together.
  # # Default: 50
  
  # elevation-scale: 35
  # # Controls the scale of elevation zones. Most land biomes belong to
  # # an elevation zone, in addition to temperature and precipitation. How far apart / close
  # # together these elevation zones are is determined by this parameter. If you want more
  # # gradual changes in the groupings of the elevation of biomes, you can increase this.
  # # Conversely, if you want more sudden changes in elevation, you can decrease this.
  # # Note - This does not affect how tall the terrain is in individual biomes, just the
  # #        elevation map that distributes biomes of similar elevation together!
  # # Default: 35

  variation-scale: 60
  # Controls biome variations within each temperature + precipitation + elevation zone.
  # Some biomes belong to the same groups, and so we have an extra variation map that
  # determines which of these biomes within the same group get generated.
  # Default: 60

  cave-biome-scale: 200
  # Controls the scale of the placement of cave biomes, larger scale = bigger areas of
  # any given cave biome, smaller scale = smaller cave biomes.
  # Default: 200

  river-spread-scale: 10
  # Controls how far / close apart rivers generally are, larger scale = further apart
  # rivers, smaller scale = closer packed together rivers.
  # Default: 10
  
  global-scale: 1
  # Modifies the scale of everything, you can use this parameter to if you
  # want just about every biome to be larger or smaller.
  # By doubling the scale, you double the length & width of everything,
  # e.g. if you have a biome that is 300 blocks wide with a scale of 1, and
  # increase that scale to 2, that biome will generate 600 blocks wide.
  # Default: 1

# Misc global config stuff

strata: # Controls global Y level ranges of strata
  deepslate:
    top: 7 # Y level where deepslate begins to replace stone
    bottom: -7 # Y level where all stone is replaced by deepslate
  bedrock:
    top: -60 # Y level where bedrock begins to replace deepslate
    bottom: -64 # Y level where all deepslate is replaced by bedrock
  bedrock-top:
    top: 319 
    bottom: 316

palette-top: # Added to the top of every palette
  - BLOCK:minecraft:bedrock: $meta.yml:strata.bedrock-top.top
  - UNDERGROUND_SKYLIGHT: $meta.yml:strata.bedrock-top.bottom

palette-bottom: # Added to the bottom of every palette
  - DEEPSLATE: $meta.yml:strata.deepslate.top
  - BEDROCK: $meta.yml:strata.bedrock.top
  - BLOCK:minecraft:bedrock: $meta.yml:strata.bedrock.bottom
  
palette-bedrock: # Added to the bottom of palettes that use their own deepslate palette
  - BEDROCK: $meta.yml:strata.bedrock.top
  - BLOCK:minecraft:bedrock: $meta.yml:strata.bedrock.bottom